version: "3.9"

services:
  # üêò Base de datos PostgreSQL para Compras (NUEVA)
  compras-db-v2:
    image: postgres:16-alpine
    container_name: compras-db-v2
    restart: unless-stopped
    environment:
      POSTGRES_USER: compras
      POSTGRES_PASSWORD: compras_pwd
      POSTGRES_DB: comprasdb2   # <- NUEVA BASE
    ports:
      - "5440:5432"    # <- NUEVO PUERTO PARA EVITAR CONFLICTO
    volumes:
      - compras_data_v2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U compras -d comprasdb2"]
      interval: 5s
      timeout: 3s
      retries: 5

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: compras-rabbit
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  compras_data_v2: